// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_render.ts";
import * as $3 from "./routes/add_module.tsx";
import * as $4 from "./routes/artwork.tsx";
import * as $5 from "./routes/benchmarks.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/manual.tsx";
import * as $8 from "./routes/showcase.tsx";
import * as $9 from "./routes/status.tsx";
import * as $10 from "./routes/std.tsx";
import * as $11 from "./routes/translations.tsx";
import * as $12 from "./routes/x/index.tsx";
import * as $13 from "./routes/x/module.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_render.ts": $2,
    "./routes/add_module.tsx": $3,
    "./routes/artwork.tsx": $4,
    "./routes/benchmarks.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/manual.tsx": $7,
    "./routes/showcase.tsx": $8,
    "./routes/status.tsx": $9,
    "./routes/std.tsx": $10,
    "./routes/translations.tsx": $11,
    "./routes/x/index.tsx": $12,
    "./routes/x/module.tsx": $13,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
