// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/add_module.tsx";
import * as $3 from "./routes/api.tsx";
import * as $4 from "./routes/artwork.tsx";
import * as $5 from "./routes/badge.ts";
import * as $6 from "./routes/benchmarks.tsx";
import * as $7 from "./routes/completions/config.ts";
import * as $8 from "./routes/completions/v1.ts";
import * as $9 from "./routes/gfm.css.ts";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/install.ts";
import * as $12 from "./routes/legacy_redirects/posts.ts";
import * as $13 from "./routes/legacy_redirects/v1.ts";
import * as $14 from "./routes/manual.tsx";
import * as $15 from "./routes/showcase.tsx";
import * as $16 from "./routes/status.tsx";
import * as $17 from "./routes/std.tsx";
import * as $18 from "./routes/translations.tsx";
import * as $19 from "./routes/x/index.tsx";
import * as $20 from "./routes/x/module.tsx";
import * as $$0 from "./islands/AddModule.tsx";
import * as $$1 from "./islands/GlobalSearch.tsx";
import * as $$2 from "./islands/HelloBar.tsx";
import * as $$3 from "./islands/VersionSelect.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/add_module.tsx": $2,
    "./routes/api.tsx": $3,
    "./routes/artwork.tsx": $4,
    "./routes/badge.ts": $5,
    "./routes/benchmarks.tsx": $6,
    "./routes/completions/config.ts": $7,
    "./routes/completions/v1.ts": $8,
    "./routes/gfm.css.ts": $9,
    "./routes/index.tsx": $10,
    "./routes/install.ts": $11,
    "./routes/legacy_redirects/posts.ts": $12,
    "./routes/legacy_redirects/v1.ts": $13,
    "./routes/manual.tsx": $14,
    "./routes/showcase.tsx": $15,
    "./routes/status.tsx": $16,
    "./routes/std.tsx": $17,
    "./routes/translations.tsx": $18,
    "./routes/x/index.tsx": $19,
    "./routes/x/module.tsx": $20,
  },
  islands: {
    "./islands/AddModule.tsx": $$0,
    "./islands/GlobalSearch.tsx": $$1,
    "./islands/HelloBar.tsx": $$2,
    "./islands/VersionSelect.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
