// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $2 from "./pages/_render.ts";
import * as $5 from "./pages/translations.tsx";
import * as $10 from "./pages/artwork.tsx";

const routes = {
  pages: {
    //"./pages/index.tsx": $0,
    //"./pages/std.tsx": $1,
    "./pages/_render.ts": $2,
    //"./pages/benchmarks.tsx": $3,
    //"./pages/manual.tsx": $4,
    "./pages/translations.tsx": $5,
    //"./pages/status.tsx": $6,
    //"./pages/_app.tsx": $7,
    //"./pages/x/index.tsx": $8,
    //"./pages/x/[...rest].tsx": $9,
    "./pages/artwork.tsx": $10,
  },
  baseUrl: import.meta.url,
};

export default routes;
