// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/index.tsx";
import * as $1 from "./pages/std.tsx";
import * as $2 from "./pages/_render.ts";
//import * as $3 from "./pages/benchmarks.tsx";
import * as $4 from "./pages/manual.tsx";
import * as $5 from "./pages/translations.tsx";
import * as $6 from "./pages/status.tsx";
import * as $7 from "./pages/_404.tsx";
//import * as $8 from "./pages/_app.tsx";
import * as $9 from "./pages/x/index.tsx";
import * as $10 from "./pages/x/module.tsx";
import * as $11 from "./pages/artwork.tsx";

const routes = {
  pages: {
    "./pages/index.tsx": $0,
    "./pages/std.tsx": $1,
    "./pages/_render.ts": $2,
    //"./pages/benchmarks.tsx": $3,
    "./pages/manual.tsx": $4,
    "./pages/translations.tsx": $5,
    "./pages/status.tsx": $6,
    "./pages/_404.tsx": $7,
    //"./pages/_app.tsx": $8,
    "./pages/x/index.tsx": $9,
    "./pages/x/module.tsx": $10,
    "./pages/artwork.tsx": $11,
  },
  baseUrl: import.meta.url,
};

export default routes;
