# Copyright 2020 the Deno authors. All rights reserved. MIT license.

# Cloudflare Worker configuration
account_id = "895762025d37fc687ecd72d7cc80204a"
zone_id = "c192cf8ac042c681023493c52edd44c8"

# shared
type = "webpack"
webpack_config = "webpack.config.js"

# default dev environment
name = "worker-dev"
workers_dev = true

# environment configuration
[env.staging]
name = "worker-staging"
route = "staging.deno.land/*"
workers_dev = false

# environment configuration
[env.production]
name = "worker"
route = "deno.land/*"
workers_dev = false
